import { Categorie } from "@/modules/anime/categorie/categorie";
import type { Metadata } from "next";
import React from 'react'
export const metadata: Metadata = {
  title: "streaming",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <Categorie/>
  )
}

export default page